# Generated by Django 4.0.4 on 2022-04-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("congregation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.IntegerField(default=0)),
                ("return_visits", models.IntegerField(default=0)),
                ("bible_studies", models.IntegerField(default=0)),
                ("placements", models.IntegerField(default=0)),
                ("videos", models.IntegerField(default=0)),
                ("remarks", models.TextField(blank=True, max_length=5000, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_change_date", models.DateTimeField(auto_now=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="congregation.publisher",
                    ),
                ),
            ],
        ),
    ]
