# Generated by Django 4.0.4 on 2022-04-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Congregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=24)),
                ("name", models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=52)),
                ("language", models.CharField(max_length=52, null=True, blank=True)),
                (
                    "congregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="congregation.congregation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "Inactive"), ("1", "Active")], max_length=5
                    ),
                ),
                ("regular_pioneer", models.BooleanField(default=False)),
                ("ministerial_servant", models.BooleanField(default=False)),
                ("elder", models.BooleanField(default=False)),
                (
                    "contact_number",
                    models.CharField(max_length=24, null=True, blank=True),
                ),
                ("email", models.EmailField(max_length=254, null=True, blank=True)),
                ("remarks", models.TextField(blank=True, max_length=5000, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="congregation.group",
                    ),
                ),
            ],
        ),
    ]
